config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :subs do
    resources :posts, only: [:index]
  end
  resources :posts, except: [:index]
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  sub_id     :integer          not null
#  author_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ActiveRecord::Base
  validates :title, :author_id, presence: true


  belongs_to :author, class_name: :User

  has_many :post_subs, dependent: :destroy, inverse_of: :post

  has_many :subs, through: :post_subs
end

app/models/post_sub.rb
class PostSub < ActiveRecord::Base
  validates :sub, :post, presence: true
  validates :sub_id, uniqueness: {scope: :post_id}

  belongs_to :sub

  belongs_to :post
end

app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :integer          not null, primary key
#  title        :string           not null
#  description  :text             not null
#  moderator_id :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Sub < ActiveRecord::Base
  validates :title, :description, :moderator_id, presence: true

  belongs_to :moderator, class_name: :User



  has_many :post_subs, dependent: :destroy, inverse_of: :sub

  has_many :posts, through: :post_subs
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  validates :username, :email, :session_token, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :password, length: {minimum: 6, allow_nil: true}
  after_initialize :ensure_session_token

  has_many :subs, foreign_key: :moderator_id

  has_many :posts, foreign_key: :author_id

  attr_reader :password

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return nil unless user
    user.is_password?(password) ? user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
  end

  private
  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def login!(user)
    logout! if logged_in?
    @current_user = user
    session[:session_token] = user.session_token
  end

  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def logged_in?
    !session[:session_token].nil?
  end

  def require_login
    redirect_to new_session_url unless logged_in?
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login, except: [:show]
  before_action :check_user_id, only: [:edit, :destroy]

  def new
    render :new

  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to post_url(@post)
    else
      redirect_to new_post_url
    end
  end

  def show
    @post = Post.find_by(id: params[:id])
    if @post
      render :show
    else
      redirect_to subs_url
    end

  end

  def edit
    @post = Post.find_by(id: params[:id])
    if @post
      render :edit
    else
      redirect_to new_post_url
    end
  end

  def update
    @post = Post.find_by(id: params[:id])
    if @post && @post.update(post_params)
      redirect_to post_url(@post)
    else
      redirect_to edit_post_url(@post)
    end

  end

  def destroy
    @post = Post.find_by(id: params[:id])
    @post.destroy
    redirect_to sub_url(@post.sub)
  end

  private
  def post_params
    params.require(:post).permit(:title, :url, :content, :author_id, sub_ids: [])
  end

  def check_user_id
    post = Post.find_by(id: params[:id])
    if post.author_id != current_user.id
      redirect_to post_url(post)
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create

    user = User.find_by_credentials(params[:user][:username], params[:user][:password])
    if user
      login!(user)
      #redirect to home page when homepage exists
      redirect_to user_url(user)
    else
      redirect_to new_session_url
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController

  before_action :require_login, except: [:index, :show]
  before_action :check_user_id, only: [:edit, :update, :destroy]

  def new
    render :new
  end

  def create
    @sub = Sub.new(sub_params)
    if @sub.save
      redirect_to sub_url(@sub)
    else
      redirect_to new_subs_url
    end
  end

  def edit
    @sub = Sub.find_by(id: params[:id])
    if @sub
      render :edit
    else
      redirect_to subs_url
    end
  end

  def update
    @sub = Sub.find_by(id: params[:id])
    if @sub && @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      redirect_to subs_url
    end
  end

  def index
    @subs = Sub.all
    render :index
  end

  def show
    @sub = Sub.find_by(id: params[:id])
    if @sub
      render :show
    else
      redirect_to subs_url
    end
  end

  def destroy
    @sub = Sub.find_by(id: params[:id])
    @sub.destroy
    redirect_to subs_url
  end

  private
  def sub_params
    params.require(:sub).permit(:title, :description, :moderator_id)
  end

  def check_user_id
    subreddit = Sub.find_by(id: params[:id])
    if subreddit.moderator_id != current_user.id
      redirect_to sub_url(subreddit)
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login!(@user)
      redirect_to user_url(@user)
    else
      fail
      render :new
    end

  end

  def show
    @user = User.find_by(id: params[:id])
    if @user
      render :show
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    '<input type="hidden" name="authenticity_token" value="#{form_authenticity_token}">'.html_safe
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RedditClone</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<footer>
<% if logged_in? %>
  <%= button_to "Logout", "/session", method: "delete" %>
  <% end %>
</footer>
</body>
</html>

app/views/posts/edit.html.erb
<h1>Edit Post: <%= @post.title %>!</h1>

<form action="<%= post_url(@post) %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="_method" value="PATCH">
  <input type="hidden" name="post[author_id]" value="<%= current_user.id %>">
  <label for="title">Title:</label>
  <input type="text" name="post[title]" id="title" value="<%= @post.title %>">
  <label for="url">URL:</label>
  <input type="text" name="post[url]" id="url" value="<%= @post.url %>">
  <label for="sub">Subreddit:</label>
  <select name="post[sub_id]">
    <% Sub.all.each do |subreddit| %>
      <option value="<%= subreddit.id %>" <%= "selected" if subreddit.id == @post.sub_id %>> <%= subreddit.title %> </option>
    <% end %>

  </select>
  <br>
  <label for="content">Content:</label>
  <br>
  <textarea name="post[content]" rows="8" cols="80"> <%= @post.content %> </textarea>

  <input type="submit" value="Edit post!">

</form>

<%= button_to "Delete Post", post_url(@post), method: :delete %>

app/views/posts/new.html.erb
<h1>Make a new Post!</h1>

<form action="<%= posts_url %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="post[author_id]" value="<%= current_user.id %>">
  <label for="title">Title:</label>
  <input type="text" name="post[title]" id="title">
  <label for="url">URL:</label>
  <input type="text" name="post[url]" id="url">
  <label for="sub">Subreddit:</label>
  <select name="post[sub_id]">
    <% Sub.all.each do |subreddit| %>
      <option value="<%= subreddit.id %>"> <%= subreddit.title %> </option>
    <% end %>

  </select>
  <br>
  <label for="content">Content:</label>
  <br>
  <textarea name="post[content]" rows="8" cols="80"></textarea>

  <input type="submit" value="Create post!">


</form>

app/views/posts/show.html.erb
<h1> <%= @post.title %>  </h1>

<section>
  <p>Subreddit: r/<%= @post.sub.title %> </p>
  <p>URL: <%= @post.url %> </p>
  <p>Content: <%= @post.content %>  </p>
  <p>Author: <%= @post.author.username %> </p>

</section>

app/views/subs/edit.html.erb
<h1>Edit r/<%= @sub.title %> </h1>
<section>
  <form action="<%= sub_url(@sub) %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="hidden" name="_method" value="PATCH">

    <label for="description">Description:</label>
    <br>
    <textarea name="sub[description]" rows="8" cols="80"> <%= @sub.description %> </textarea>

    <br>
    <input type="submit" value="Edit subreddit">

  </form>
</section>

app/views/subs/index.html.erb
<h1>All Subreddits</h1>

<section>
  <% @subs.each do |subreddit| %>
    <%= link_to subreddit.title, "/subs/#{subreddit.id}", method: 'get'  %>
    <br>
  <% end %>
</section>

app/views/subs/new.html.erb
<h1>Create a new Subreddit!</h1>

<section>
  <form action="<%= subs_url %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="hidden" name="sub[moderator_id]" value="<%= current_user.id %>">
    <label for="title">Title:</label>
    <input type="text" name="sub[title]" id="title">
    <label for="description">Description:</label>
    <textarea name="sub[description]" rows="8" cols="80"></textarea>

    <input type="submit" value="Create new subreddit">



  </form>
</section>

app/views/subs/show.html.erb
<h1>Welcome to r/<%= @sub.title %></h1>
<p><%= @sub.description %></p>
<p>Moderated by <%= @sub.moderator.username %> </p>
<% #posts for sub go here %>

app/views/users/new.html.erb
<h1>Welcome to Reddit!</h1>
<h3>Sign up here</h3>

<section>
  <form action="<%= users_url %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <label for="username">Username:</label>
    <input type="text" name="user[username]" id="username">
    <label for="email">Email:</label>
    <input type="text" name="user[email]" id="email">
    <label for="password">Password:</label>
    <input type="password" name="user[password]" id="password">

    <br>
    <input type="submit">
  </form>
</section>

app/views/users/show.html.erb
<h1>Hello, <%= @user.username %>!</h1>